openapi: 3.0.4
info:
  title: Words to Numbers
  description: Words to Numbers is a simple tool for converting words to numbers. It returns the words in numbers.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/wordstonumbers:
    get:
      summary: Convert Words
      description: Words to Numbers is a simple tool for converting words to numbers. It returns the words in numbers.
      operationId: wordstonumbers
      parameters:
      - name: words
        in: query
        schema:
          type: string
        required: false
        description: The words to convert to numbers
        example: seven thousand six hundred and twenty
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  number: '7620'
                  words: seven thousand, six hundred twenty
                  ordinal: seven thousand, six hundred twentieth
                  numberOfDigits_numeric: 4
                  numberOfDigits_words: four
                  eachNumber:
                  - seven
                  - six
                  - two
                  - zero
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
